[2025-09-11T22:31:42.264+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-11T22:31:42.289+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_share_pipeline.rw_extract_extraction_market_share_job manual__2025-09-11T22:31:36.639082+00:00 [queued]>
[2025-09-11T22:31:42.300+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_share_pipeline.rw_extract_extraction_market_share_job manual__2025-09-11T22:31:36.639082+00:00 [queued]>
[2025-09-11T22:31:42.300+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-09-11T22:31:42.317+0000] {taskinstance.py:2890} INFO - Executing <Task(CloudRunExecuteJobOperator): rw_extract_extraction_market_share_job> on 2025-09-11 22:31:36.639082+00:00
[2025-09-11T22:31:42.327+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'market_share_pipeline', 'rw_extract_extraction_market_share_job', 'manual__2025-09-11T22:31:36.639082+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/market-share.py', '--cfg-path', '/tmp/tmpcabo25zv']
[2025-09-11T22:31:42.327+0000] {standard_task_runner.py:105} INFO - Job 114: Subtask rw_extract_extraction_market_share_job
[2025-09-11T22:31:42.329+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=445) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-11T22:31:42.329+0000] {standard_task_runner.py:72} INFO - Started process 474 to run task
[2025-09-11T22:31:42.386+0000] {task_command.py:467} INFO - Running <TaskInstance: market_share_pipeline.rw_extract_extraction_market_share_job manual__2025-09-11T22:31:36.639082+00:00 [running]> on host 3f86374fd34d
[2025-09-11T22:31:42.469+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='market_share_pipeline' AIRFLOW_CTX_TASK_ID='rw_extract_extraction_market_share_job' AIRFLOW_CTX_EXECUTION_DATE='2025-09-11T22:31:36.639082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-11T22:31:36.639082+00:00'
[2025-09-11T22:31:42.469+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-11T22:31:42.494+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-09-11T22:31:42.495+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-09-11T22:31:42.496+0000] {credentials_provider.py:402} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2025-09-11T22:31:43.638+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-09-11T22:31:43.649+0000] {taskinstance.py:289} INFO - Pausing task as DEFERRED. dag_id=market_share_pipeline, task_id=rw_extract_extraction_market_share_job, run_id=manual__2025-09-11T22:31:36.639082+00:00, execution_date=20250911T223136, start_date=20250911T223142
[2025-09-11T22:31:43.650+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-11T22:31:43.666+0000] {local_task_job_runner.py:260} INFO - Task exited with return code 100 (task deferral)
[2025-09-11T22:31:43.667+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-09-11T22:38:26.566+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-11T22:38:26.579+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_share_pipeline.rw_extract_extraction_market_share_job manual__2025-09-11T22:31:36.639082+00:00 [queued]>
[2025-09-11T22:38:26.584+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_share_pipeline.rw_extract_extraction_market_share_job manual__2025-09-11T22:31:36.639082+00:00 [queued]>
[2025-09-11T22:38:26.584+0000] {taskinstance.py:2865} INFO - Resuming after deferral
[2025-09-11T22:38:26.594+0000] {taskinstance.py:2890} INFO - Executing <Task(CloudRunExecuteJobOperator): rw_extract_extraction_market_share_job> on 2025-09-11 22:31:36.639082+00:00
[2025-09-11T22:38:26.603+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'market_share_pipeline', 'rw_extract_extraction_market_share_job', 'manual__2025-09-11T22:31:36.639082+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/market-share.py', '--cfg-path', '/tmp/tmpx4idjpoc']
[2025-09-11T22:38:26.604+0000] {standard_task_runner.py:105} INFO - Job 115: Subtask rw_extract_extraction_market_share_job
[2025-09-11T22:38:26.605+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1331) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-11T22:38:26.605+0000] {standard_task_runner.py:72} INFO - Started process 1343 to run task
[2025-09-11T22:38:26.636+0000] {task_command.py:467} INFO - Running <TaskInstance: market_share_pipeline.rw_extract_extraction_market_share_job manual__2025-09-11T22:31:36.639082+00:00 [running]> on host 3f86374fd34d
[2025-09-11T22:38:26.682+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-11T22:38:26.693+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1816, in resume_execution
    return execute_callable(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/cloud_run.py", line 331, in execute_complete
    raise AirflowException(
airflow.exceptions.AirflowException: Operation failed with error code [10] and error message [Task cr-juridico-extracao-market-share-job-dev-7fnbs-task0 failed with message: The container exited with an error.]
[2025-09-11T22:38:26.698+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=market_share_pipeline, task_id=rw_extract_extraction_market_share_job, run_id=manual__2025-09-11T22:31:36.639082+00:00, execution_date=20250911T223136, start_date=20250911T223142, end_date=20250911T223826
[2025-09-11T22:38:26.720+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-11T22:38:26.721+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 115 for task rw_extract_extraction_market_share_job (Operation failed with error code [10] and error message [Task cr-juridico-extracao-market-share-job-dev-7fnbs-task0 failed with message: The container exited with an error.]; 1343)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1816, in resume_execution
    return execute_callable(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/cloud_run.py", line 331, in execute_complete
    raise AirflowException(
airflow.exceptions.AirflowException: Operation failed with error code [10] and error message [Task cr-juridico-extracao-market-share-job-dev-7fnbs-task0 failed with message: The container exited with an error.]
[2025-09-11T22:38:26.739+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-11T22:38:26.758+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-11T22:38:26.760+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
